sudo: required	
language: android	
android:	
  components:	
    - build-tools-27.0.3	
    - android-19	
    - android-23	
before_install:	
  - sudo chmod +x gradlew	
notifications:	
  email:	
    recipients:	
      - guberti@eastsideprep.org	
    on_success: never	
    on_failure: always
