language: python
android:
  components:
    - build-tools-25.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - android-N